### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by marcozer** [mebitek/tui-deck#2]
I get this error when launching the program usign Deck on NC 27 and 28 
FATAL ERROR: Error getting boards: Get "marcozer.org/index.php/apps/deck/api/v1.1/boards": unsupported protocol scheme ""

**Comment by mebitek** [comment]
you need to use a complete uri like http://marcozer.org

**Comment by marcozer** [comment]
Thank you @mebitek  for your quick answer and your great work. 
I also get this error when I configured the complete url in the json file (Deck 1.11.4)

```
/home/marcozer/tui-deck 
Getting boards...
panic: mkdir /db: permission denied

goroutine 1 [running]:
main.main()
        /home/mebitek/workspace/mebitek/tui-deck/main.go:60 +0xefb
```

**Comment by mebitek** [comment]
the  json config should look like this:

{
  "username": "mebitek",
  "password": "******",
  "url": "http://marcozer.org",
  "color": "#BF40BF",
  "configDir": "/home/mebitek/.config/tui-deck/"
}

you are trying to create the db dir into the main server root. check the configDir value

**Comment by marcozer** [comment]
Thank you for your help and sorry for not tagging properly the issue. 

I added the configDir line in the json and I am still getting the same error as before : 

(I use TFA in nextcloud and I created a specific app password)

```
│FATAL ERROR: Error getting boards: Get "/index.php/apps/deck/api/v1.1/boards":│
│ unsupported protocol scheme ""                                               │
```

**Comment by mebitek** [comment]
seems it is missing the whole  url and schema. could you please post your config?

**Comment by marcozer** [comment]
Here is my config : 

```
{
  "username": "marcozer",
  "password": "[specific app password]",
  "url": "https://marcozer.org",
  "color": "#BF40BF"
  "configDir": "/home/marcozer/.config/tui-deck/"
}
```

**Comment by mebitek** [comment]
a coma is missing after color:

{
  "username": "marcozer",
  "password": "[specific app password]",
  "url": "https://marcozer.org",
  "color": "#BF40BF"**,**
  "configDir": "/home/marcozer/.config/tui-deck/"
}

**Comment by marcozer** [comment]
Oh... I am really sorry 
everything works fine now 
thank you for your time
