### ISSUE TITLE
No connection with x.509 self signed ssl certificate

### ISSUE THREAD

**Issue by ziriuz84** [mebitek/tui-deck#3]
It seems impossible to connect to a Nextcloud instance if it has a self signed certificate that can't be verified from CA. Maybe it will be a good option in config file something to disable verification? I've my instance behind vpn and I can't use Let's Encrypt or similar services

**Comment by mebitek** [comment]
new release 0.5.16 should fix it. please try and report feedback

add "insecure": true to your config and verify that tui-deck version is 0.5.16

**Comment by ziriuz84** [comment]
I added a PR (#4 ) to add it to documentation
